# Site settings
title:       Qimu's Code and Life | 郑淇木的代码及日常
email:       zheng.qm@163.com
author_en:      Qimu Zheng
author_cn:      郑淇木
description: "郑淇木的博客  Qimu Zheng's Blog"
baseurl:     ""
url:         "https://zhengqm.github.io"

gems: [jekyll-paginate]
encoding: utf-8
# Google analytics
google_analytics: UA-64116908-1

excerpt_separator: ""

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false


# Disqus post comments
# (leave blank to disable Disqus)
#disqus_shortname: qimublog

# Social icons
show_social_icons: true
weibo_id:          2172274364
github_username:   zhengqm
stackoverflow_id:
twitter_username:  zheng_qm
google_plus_id:
linkedin_username: qimu-zheng-6b72a484
angellist_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: '分享到：'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false
share_weibo: true


# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     8
sass:
  compressed: true
