# Site settings
title:       Qimu's Code and Life
email:       zheng.qm@163.com
author:      郑淇木 / Qimu Zheng
description: "郑淇木的代码及日常"
baseurl:     ""
url:         "http://zhengqm.github.io"

# Google analytics
google_analytics: UA-64116908-1

excerpt_separator: ""

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: qimublog

# Social icons
show_social_icons: true
weibo_id:          2172274364
github_username:
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
angellist_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     5
sass:
  compressed: true
